# Práctica 3. Representación Vectorial.
### Lingüística Computacional 2026-2
#### Cuerpo Académico
**Dra.** María Ximena Gutiérrez Vasques

**Ayud.** Ximena de la Luz Contreras Mendoza

**Lab.** Diego Alberto Barriga Martínez

#### Alumno
Toporek Coca Eric - **314284987**

## 1 Matrices dispersas y búsqueda de documentos

Tomaremos como referencia los parrafos introductorios de sitios de Wikipedia, sin tomar en cuenta que tan fidedigna pueda ser la información que contiene. El listado se da como sigue:

1. [Salvador Allende](https://es.wikipedia.org/wiki/Salvador_Allende#)
2. [Pinochet](https://es.wikipedia.org/wiki/Augusto_Pinochet)
3. [Golpe de Estado en Chile de 1973](https://es.wikipedia.org/wiki/Golpe_de_Estado_en_Chile_de_1973)
4. [Árbol de Manzano](https://es.wikipedia.org/wiki/Malus_domestica)
5. [Árbol de Cacao](https://es.wikipedia.org/wiki/Theobroma_cacao)

In [3]:
doc_1 = """Salvador Guillermo Allende Gossens​ (Santiago, 26 de junio de 1908-Santiago, 11 de septiembre de 1973) fue un médico cirujano y político socialista chileno, presidente de Chile —el segundo nacido en el siglo XX— desde el 3 de noviembre de 1970 hasta el 11 de septiembre de 1973. Su gobierno, caracterizado por un socialismo democrático, acabó abruptamente con un golpe de Estado, durante el cual optó por suicidarse mientras militares comandados por Augusto Pinochet tomaban el Palacio de la Moneda. Participó en política desde sus estudios en la Universidad de Chile. Fue sucesivamente diputado (1937-1939), ministro de Salubridad (1939-1942) del gobierno de Pedro Aguirre Cerda, y senador (1945-1970), ejerciendo la presidencia de la cámara alta del Congreso (1966-1969). Además, fue secretario general del Partido Socialista de Chile (1942-1943). Fue candidato a la presidencia de la República en cuatro oportunidades: en las elecciones de 1952 obtuvo el 5,45 % de los votos; en las de 1958, el 28,85 % de los votos, tras el electo Jorge Alessandri; en las de 1964, el 38,93 % de los votos, tras el electo Eduardo Frei Montalva; y, finalmente, en las de 1970, a tres bandas, consiguió la primera mayoría simple con el 36,63 % de los votos, siendo en definitiva ratificado por el Congreso Nacional. De ese modo, Allende se convirtió en el primer presidente marxista del mundo en acceder al poder a través de elecciones generales en un Estado democrático de derecho. Su gobierno fue apoyado por la Unidad Popular, una coalición de partidos de izquierda, y destacó tanto por el intento de establecer un Estado socialista aferrándose a los medios democráticos y constitucionales del Poder Ejecutivo —la «vía chilena al socialismo»—, como por proyectos como la nacionalización del cobre, la estatización de las áreas «claves» de la economía y la profundización de la reforma agraria iniciada por su antecesor, Eduardo Frei Montalva. El gobierno de la Unidad Popular se vio envuelto en la polarización política internacional de la Guerra Fría​ y sufrió de la persistente intervención por parte del gobierno estadounidense de Richard Nixon y la Agencia Central de Inteligencia (CIA) con el fin de provocar un cambio de régimen. En medio de una crisis económica (llegando a tener una inflación del 606 % en 1973), social y a tres años antes del fin de su mandato constitucional, el gobierno de Salvador Allende terminó abruptamente el 11 de septiembre de 1973 mediante un golpe de Estado en el que participaron las tres ramas de las Fuerzas Armadas y el cuerpo de Carabineros.​ Ese mismo día, después de que el Palacio de La Moneda fuese bombardeado por aviones y tanques, Allende se suicidó. Tras el fin de su gobierno, el general Augusto Pinochet encabezó una dictadura militar que se extendió por más de dieciséis años, lo que puso fin al período de la República Presidencial."""
doc_2 = """Augusto José Ramón Pinochet Ugarte (Valparaíso, 25 de noviembre de 1915-Santiago, 10 de diciembre de 2006) fue un militar, político y dictador chileno que gobernó Chile entre 1973 y 1990 durante la dictadura militar. El presidente Salvador Allende lo designó comandante en jefe del Ejército de Chile el 23 de agosto de 1973, en reemplazo del renunciado general Carlos Prats. El 11 de septiembre del mismo año, en medio de una crisis política, económica y social, dirigió junto a José Toribio Merino y Gustavo Leigh un golpe de Estado que derrocó al gobierno democrático de la coalición de partidos políticos de izquierda denominada Unidad Popular, poniendo fin al período de la República Presidencial.​ Desde ese momento, gobernó el país, primero como presidente de la Junta Militar de Gobierno —al que se sumó el título de jefe supremo de la Nación el 27 de junio de 1974, que le confirió el poder ejecutivo— y luego, a partir del 16 de diciembre de 1974, como presidente de la República, cargo que fue ratificado tras un cuestionado plebiscito y la promulgación de una nueva Constitución en 1980. Su mandato acabó por la vía democrática mediante otro plebiscito realizado in 1988, tras el cual fue sustituido —luego de realizarse elecciones presidenciales y parlamentarias— por Patricio Aylwin el 11 de marzo de 1990. Pinochet se mantuvo como comandante en jefe del Ejército hasta el 10 de marzo de 1998 y al día siguiente asumió como senador vitalicio, cargo que ejerció efectivamente por un par de meses. Bajo la influencia de los «Chicago Boys», economistas orientados al libre mercado, el nuevo régimen implementó la liberalización económica, incluida la estabilización monetaria. También eliminó las protecciones arancelarias para la industria local, prohibió los sindicatos y privatizó la seguridad social y empresas estatales. Estas políticas produjeron un inicial crecimiento económico, que Milton Friedman denominó el «milagro de Chile», pero que contrasta con un aumento dramático en la desigualdad de ingresos y que habría llevado a una devastadora crisis económica en 1982 influida por el contexto global de la segunda crisis del petróleo detonada en 1979, por la revolución islámica en Irán y la subsecuente guerra Irán-Irak que comenzó en 1980.​ Durante la mayor parte de la década de 1990, Chile fue la economía de mejor desempeño en América Latina, aunque el legado de las reformas de Pinochet sigue en disputa. Durante la dictadura se cometieron graves y diversas violaciones de los derechos humanos. Pinochet persiguió a izquierdistas, socialistas y críticos políticos, lo que provocó el asesinato de entre 1200 y 3200 personas,​ la detención de unas 80 000 personas y la tortura de decenas de miles. Según el gobierno chileno, el número de ejecuciones y desapariciones forzadas fue de 3095. Pinochet fue arrestado, en virtud de una orden internacional de arresto expedida por un juez español, tras una visita a Londres el 10 de octubre de 1998 en relación con numerosas violaciones de derechos humanos. Luego de una batalla legal, fue liberado por motivos de salud y regresó a Chile el 3 de marzo de 2000. En 2004, el juez chileno Juan Guzmán Tapia dictaminó que Pinochet era médicamente apto para enfrentar un juicio y lo puso bajo arresto domiciliario. Al momento de la muerte de Pinochet, el 10 de diciembre de 2006, en Chile aún se encontraban pendientes 300 cargos penales por numerosas violaciones de derechos humanos durante su mandato de casi diecisiete años, además de casos de evasión de impuestos y malversación durante y después de dicho periodo. También el juez Muñoz estimó que acumuló ilícitamente al menos 28 millones de dólares."""
doc_3 = """El golpe de Estado en Chile del 11 de septiembre de 1973 fue una acción militar llevada a cabo por las Fuerzas Armadas de Chile conformadas por la Armada, la Fuerza Aérea, Cuerpo de Carabineros y el Ejército, para derrocar al presidente socialista Salvador Allende y al gobierno de la Unidad Popular. Tropas del ejército y aviones de la Fuerza Aérea atacaron el Palacio de La Moneda, la sede de gobierno. Allende se suicidó mientras las tropas militares ingresaban al Palacio. Este golpe dio origen al establecimiento de una junta militar liderada por Augusto Pinochet. Chile, que hasta ese entonces se mantenía como una de las democracias más estables en América Latina, entró en una dictadura militar que se extendió hasta 1990. Durante este periodo, se cometieron sistemáticas violaciones a los derechos humanos,​ se limitó la libertad de expresión, se suprimieron los partidos políticos y se disolvió el Congreso Nacional. Salvador Allende asumió en 1970 la presidencia de Chile, siendo el primer político de orientación marxista en el mundo que accedió al poder a través de elecciones generales en un Estado de Derecho. Su gobierno, de marcado carácter reformista, produjo una creciente polarización política en la sociedad y una dura crisis económica que desembocó en una fuerte convulsión social. Esto llevó a una acusación constitucional por parte del Congreso poco antes del golpe. Sin embargo, la posibilidad de ejecutar un golpe de Estado contra el gobierno de Allende existió incluso antes de su elección. El gobierno de Estados Unidos, dirigido por el presidente Richard Nixon y su secretario de Estado Henry Kissinger, influyeron decisivamente en grupos opositores a Allende, financiando y apoyando activamente las condiciones para la ejecución de un golpe de Estado. Dentro de estas acciones se encuentran el asesinato del general René Schneider y el Tanquetazo, una sublevación militar el 29 de junio de 1973. Según el historiador Sebastián Hurtado, la ayuda estadounidense al golpe habría sido indirecta, afirmando que «no hay evidencia documental que sostenga que Washington actuó activamente en la coordinación y ejecución de las acciones del 11 de septiembre de 1973 (mismo)». Sin embargo, el interés de Richard Nixon desde el principio fue que el gobierno de Allende no fuese consolidado en el tiempo. Tras el Tanquetazo, grupos dentro de la Armada de Chile planearon derrocar al gobierno, al que posteriormente se sumaron los altos mandos de la Fuerza Aérea y grupos dentro de Carabineros. Días antes de la fecha planificada para la acción militar, se sumó Augusto Pinochet, comandante en jefe del Ejército. En la mañana del 11 de septiembre de 1973, las cúpulas de las Fuerzas Armadas y de Orden lograron rápidamente controlar gran parte del país exigiendo la renuncia inmediata de Salvador Allende, quien se refugió en la sede de gobierno. Hasta hoy este evento histórico divide al país (según encuesta CERC-MORI realizada en el 50.º aniversario del suceso, 36 % de chilenos afirma que militares tuvieron razón en su actuar). Testimonio de la discrepancia es que algunos ideólogos y partidarios del golpe de Estado aun lo califican o justifican como «pronunciamiento militar», denominación que opositores rechazan por considerarla eufemística o agraviante."""
doc_4 = """Malus domestica, el manzano europeo o manzano común, es un árbol de la familia de las rosáceas, cultivado por su fruto, apreciado como alimento. Su domesticación parece haber comenzado hace más de 15 000 años en la región comprendida al oeste de las montañas Tian Shan, frontera entre Kazajistán y China. Fue introducido en Europa por los romanos y en la actualidad existen unas 1000 variedades/cultivares, como resultado de innumerables hibridaciones entre formas silvestres. El fruto es una gran fuente de vitaminas. Es un árbol de mediano tamaño (4 m de altura), inerme, caducifolio, de copa redondeada abierta y numerosas ramas que se desarrollan casi horizontalmente. El tronco tiene corteza agrietada que se desprende en placas. Las hojas, estipuladas y cortamente pecioladas, son ovaladas, acuminadas u obtusas, de base cuneada o redondeada, generalmente de bordes aserradas pero ocasionalmente sub-enteras, de fuerte color verde y con pubescencia en el envés. Al estrujarlas despiden un agradable aroma. La inflorescencia es una cima umbeliforme o corimbiforme con 4-8 flores hermafroditas de ovario ínfero, siendo la central la primera en formarse en posición terminal, resultando la más desarrollada y competitiva. A esta se le llama comúnmente «flor reina» y generalmente produce los frutos de mayor tamaño y calidad. Dichas flores son hermafroditas, con un cáliz de cinco sépalos, una corola de 5 pétalos blancos, redondeados, frecuentemente veteados de rojo o rosa, con uña milimétrica y 20 estambres. El manzano florece en primavera antes de la aparición anual de sus hojas. El fruto, la manzana, es un pomo de 30-100 por 35-110 mm, globoso, con restos del cáliz en el ápice, verde, amarillo, rojizo, etc. con semillas de 7-8 por 4 mm. La manzana suele madurar hacia el otoño. La del manzano silvestre se diferencia por un color verde amarillento en su piel y de sabor agrio."""
doc_5 = """Theobroma cacao es el nombre científico que recibe el árbol del cacao o cacaotero, nativo de regiones tropicales subtropicales de América del sur: América tropical, planta de hoja perenne de la familia Malvaceae. Theobroma significa, en griego, «alimento de los dioses». La palabra cacao se cree que viene de los lenguajes de la familia mixe-zoque que habrían hablado los olmecas.​ En maya yucateco, kaj significa amargo y kab significa jugo. Alternativamente, algunos lingüistas[¿quién?] proponen la teoría de que en el correr del tiempo pasó por varias transformaciones fonéticas que dieron paso a la palabra cacaoatl, la cual evolucionó después a cacao. El árbol de cacao necesita de humedad y de calor. Es de hoja perenne y siempre se encuentra en floración, crece entre los 5 y los 10 m de altura. Requiere sombra (crecen a la sombra de otros árboles más grandes como Inga edulis y platanero), protección del viento y un suelo rico y poroso, pero no se desarrolla bien en las tierras bajas cálidas. Su altura ideal es, más o menos, a 400 m s. n. m. El terreno debe ser rico en nitrógeno, magnesio y en potasio, y el clima húmedo, con una temperatura entre los 20 °C y los 30 °C. Árbol de pequeña talla, perennifolio, de 4 a 7 m de altura si es cultivado, en su forma silvestre puede crecer hasta 20 m. Hojas grandes, alternas, colgantes, elípticas u oblongas, de punta larga, ligeramente gruesas, margen liso, cuelgan de un pecíolo. El tronco generalmente es recto, las ramas primarias se forman en verticilos terminales con tres a seis ramillas y al conjunto se le llama "molinillo". Es una especie cauliflora, es decir, las flores aparecen insertadas sobre el tronco o las viejas ramificaciones. Corteza de color castaño oscuro, agrietada, áspera y delgada. Flores en racimos a lo largo del tronco y de las ramas, de color rosa, púrpura y blanco en forma de estrella. El fruto es una baya grande comúnmente denominada mazorca, carnosa, oblonga a ovada, de color amarilla o purpúrea, de 15 a 30 cm de largo por 7 a 10 cm de grueso, puntiaguda y con canales longitudinales, cada mazorca contiene en general entre treinta y cuarenta semillas incrustadas en una masa de pulpa desarrollada de las capas externas de la testa. El fruto se vuelve rojo o amarillo purpúreo y pesa aproximadamente 450 g cuando madura (de 15 a 30 cm de largo por 7 a 12 de ancho). Un árbol comienza a rendir cuando tiene cuatro o cinco años. En un año, cuando madura, puede tener 6000 flores pero solo veinte maracas. A pesar de que sus frutos maduran durante todo el año, normalmente se realizan dos cosechas: la principal (que empieza hacia el final de la estación lluviosa y continúa hasta el inicio de la estación seca) y la intermedia (al principio del siguiente periodo de lluvias), y son necesarios de cinco a seis meses entre su fertilización y su recolección."""

### Query "Tramposa"
A continuación se presenta un nuevo documento (`query_tramposa`) dirigido a un **tema completamente ajeno** a los documentos principales: **la Exploración Espacial y Astronomía**. Sin embargo, la redacción ha sido forzada para incorporar una gran cantidad de términos frecuentes de las dos temáticas del corpus (Historia de Chile y Botánica).

**Palabras infiltradas de Botánica:** terreno rico, árbol, hojas, madura, fruto, semilla, clima húmedo, ramas, corteza agrietada, sombra, de gran tamaño.
**Palabras infiltradas de Historia:** presidente, gobierno, golpe, estado, régimen, intervención, fuerzas, poder, elecciones.

In [1]:
query_tramposa = """La agencia espacial instaló su centro de control sobre un terreno rico y poroso, desde donde el presidente de la misión ejerce el poder sobre las operaciones lunares. El cohete, diseñado como un árbol de gran tamaño y con una gruesa corteza agrietada para resistir el calor, inicia su despegue tras un fuerte golpe de ignición, escapando del Estado terrestre y del clima húmedo de la región. Una vez en el vacío, el satélite crece a la sombra de los grandes planetas, extendiendo sus paneles solares como si fueran hojas perennes y ramas metálicas. Durante su órbita, debe evitar la intervención de campos magnéticos que actúan como fuerzas arrolladoras sobre sus sistemas. Su gobierno interno procesa enormes cantidades de datos a medida que la misión madura en años luz. Los científicos monitorean este régimen constante, esperando que tras diversas elecciones de trayectoria, la nave logre recolectar valiosas semillas estelares, dando a la humanidad un fruto carnoso en forma de conocimiento en medio de la inmensidad universal."""

#### Vectorización

In [4]:
documents = [doc_1,doc_2,doc_3,doc_4,doc_5,query_tramposa]

In [5]:
import re
from nltk.tokenize import word_tokenize


def simple_preprocess(text: str):
    tokens = word_tokenize(text.lower(), language="spanish")
    # Ignoramos signos de puntuación y palabras de longitud 1
    return [word for word in tokens if word.isalnum() and len(word) > 1 and not re.match(r"\d+", word)]

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
vectorizer = CountVectorizer(tokenizer=simple_preprocess, token_pattern=None)

In [8]:
bag_of_words_corpus = vectorizer.fit_transform(documents)

In [10]:
diccionario = vectorizer.vocabulary_

In [11]:
sorted(diccionario.items(), key=lambda x: x[1])

[('abierta', 0),
 ('abruptamente', 1),
 ('acabó', 2),
 ('acceder', 3),
 ('accedió', 4),
 ('acciones', 5),
 ('acción', 6),
 ('activamente', 7),
 ('actualidad', 8),
 ('actuar', 9),
 ('actuó', 10),
 ('actúan', 11),
 ('acuminadas', 12),
 ('acumuló', 13),
 ('acusación', 14),
 ('además', 15),
 ('aferrándose', 16),
 ('afirma', 17),
 ('afirmando', 18),
 ('agencia', 19),
 ('agosto', 20),
 ('agradable', 21),
 ('agraria', 22),
 ('agraviante', 23),
 ('agrietada', 24),
 ('agrio', 25),
 ('aguirre', 26),
 ('al', 27),
 ('alessandri', 28),
 ('algunos', 29),
 ('alimento', 30),
 ('allende', 31),
 ('alta', 32),
 ('alternas', 33),
 ('alternativamente', 34),
 ('altos', 35),
 ('altura', 36),
 ('amargo', 37),
 ('amarilla', 38),
 ('amarillento', 39),
 ('amarillo', 40),
 ('américa', 41),
 ('ancho', 42),
 ('aniversario', 43),
 ('antecesor', 44),
 ('antes', 45),
 ('anual', 46),
 ('aparecen', 47),
 ('aparición', 48),
 ('apoyado', 49),
 ('apoyando', 50),
 ('apreciado', 51),
 ('aproximadamente', 52),
 ('apto', 53),
 ('arancelarias', 54),
 ('armada', 55),
 ('armadas', 56),
 ('aroma', 57),
 ('arrestado', 58),
 ('arresto', 59),
 ('arrolladoras', 60),
 ('aserradas', 61),
 ('asesinato', 62),
 ('asumió', 63),
 ('atacaron', 64),
 ('augusto', 65),
 ('aumento', 66),
 ('aun', 67),
 ('aunque', 68),
 ('aviones', 69),
 ('aylwin', 70),
 ('ayuda', 71),
 ('aérea', 72),
 ('año', 73),
 ('años', 74),
 ('aún', 75),
 ('bajas', 76),
 ('bajo', 77),
 ('bandas', 78),
 ('base', 79),
 ('batalla', 80),
 ('baya', 81),
 ('bien', 82),
 ('blanco', 83),
 ('blancos', 84),
 ('bombardeado', 85),
 ('bordes', 86),
 ('boys', 87),
 ('cabo', 88),
 ('cacao', 89),
 ('cacaoatl', 90),
 ('cacaotero', 91),
 ('cada', 92),
 ('caducifolio', 93),
 ('calidad', 94),
 ('califican', 95),
 ('calor', 96),
 ('cambio', 97),
 ('campos', 98),
 ('canales', 99),
 ('candidato', 100),
 ('cantidades', 101),
 ('capas', 102),
 ('carabineros', 103),
 ('caracterizado', 104),
 ('cargo', 105),
 ('cargos', 106),
 ('carlos', 107),
 ('carnosa', 108),
 ('carnoso', 109),
 ('carácter', 110),
 ('casi', 111),
 ('casos', 112),
 ('castaño', 113),
 ('cauliflora', 114),
 ('central', 115),
 ('centro', 116),
 ('cerda', 117),
 ('chicago', 118),
 ('chile', 119),
 ('chilena', 120),
 ('chileno', 121),
 ('chilenos', 122),
 ('china', 123),
 ('cia', 124),
 ('científico', 125),
 ('científicos', 126),
 ('cima', 127),
 ('cinco', 128),
 ('cirujano', 129),
 ('claves', 130),
 ('clima', 131),
 ('cm', 132),
 ('coalición', 133),
 ('cobre', 134),
 ('cohete', 135),
 ('colgantes', 136),
 ('color', 137),
 ('comandados', 138),
 ('comandante', 139),
 ('comenzado', 140),
 ('comenzó', 141),
 ('cometieron', 142),
 ('comienza', 143),
 ('como', 144),
 ('competitiva', 145),
 ('comprendida', 146),
 ('común', 147),
 ('comúnmente', 148),
 ('con', 149),
 ('condiciones', 150),
 ('confirió', 151),
 ('conformadas', 152),
 ('congreso', 153),
 ('conjunto', 154),
 ('conocimiento', 155),
 ('considerarla', 156),
 ('consiguió', 157),
 ('consolidado', 158),
 ('constante', 159),
 ('constitucional', 160),
 ('constitucionales', 161),
 ('constitución', 162),
 ('contexto', 163),
 ('contiene', 164),
 ('continúa', 165),
 ('contra', 166),
 ('contrasta', 167),
 ('control', 168),
 ('controlar', 169),
 ('convirtió', 170),
 ('convulsión', 171),
 ('coordinación', 172),
 ('copa', 173),
 ('corimbiforme', 174),
 ('corola', 175),
 ('correr', 176),
 ('cortamente', 177),
 ('corteza', 178),
 ('cosechas', 179),
 ('crece', 180),
 ('crecen', 181),
 ('crecer', 182),
 ('creciente', 183),
 ('crecimiento', 184),
 ('cree', 185),
 ('crisis', 186),
 ('críticos', 187),
 ('cual', 188),
 ('cuando', 189),
 ('cuarenta', 190),
 ('cuatro', 191),
 ('cuelgan', 192),
 ('cuerpo', 193),
 ('cuestionado', 194),
 ('cultivado', 195),
 ('cuneada', 196),
 ('cálidas', 197),
 ('cáliz', 198),
 ('cámara', 199),
 ('cúpulas', 200),
 ('dando', 201),
 ('datos', 202),
 ('de', 203),
 ('debe', 204),
 ('decenas', 205),
 ('decir', 206),
 ('decisivamente', 207),
 ('definitiva', 208),
 ('del', 209),
 ('delgada', 210),
 ('democracias', 211),
 ('democrática', 212),
 ('democrático', 213),
 ('democráticos', 214),
 ('denominación', 215),
 ('denominada', 216),
 ('denominó', 217),
 ('dentro', 218),
 ('derecho', 219),
 ('derechos', 220),
 ('derrocar', 221),
 ('derrocó', 222),
 ('desapariciones', 223),
 ('desarrolla', 224),
 ('desarrollada', 225),
 ('desarrollan', 226),
 ('desde', 227),
 ('desembocó', 228),
 ('desempeño', 229),
 ('designó', 230),
 ('desigualdad', 231),
 ('despegue', 232),
 ('despiden', 233),
 ('desprende', 234),
 ('después', 235),
 ('destacó', 236),
 ('detención', 237),
 ('detonada', 238),
 ('devastadora', 239),
 ('dichas', 240),
 ('dicho', 241),
 ('diciembre', 242),
 ('dictador', 243),
 ('dictadura', 244),
 ('dictaminó', 245),
 ('diecisiete', 246),
 ('dieciséis', 247),
 ('dieron', 248),
 ('diferencia', 249),
 ('dio', 250),
 ('dioses', 251),
 ('diputado', 252),
 ('dirigido', 253),
 ('dirigió', 254),
 ('discrepancia', 255),
 ('diseñado', 256),
 ('disolvió', 257),
 ('disputa', 258),
 ('diversas', 259),
 ('divide', 260),
 ('documental', 261),
 ('domestica', 262),
 ('domesticación', 263),
 ('domiciliario', 264),
 ('donde', 265),
 ('dos', 266),
 ('dramático', 267),
 ('dura', 268),
 ('durante', 269),
 ('década', 270),
 ('día', 271),
 ('días', 272),
 ('dólares', 273),
 ('economistas', 274),
 ('economía', 275),
 ('económica', 276),
 ('económico', 277),
 ('eduardo', 278),
 ('edulis', 279),
 ('efectivamente', 280),
 ('ejecuciones', 281),
 ('ejecución', 282),
 ('ejecutar', 283),
 ('ejecutivo', 284),
 ('ejerce', 285),
 ('ejerciendo', 286),
 ('ejerció', 287),
 ('ejército', 288),
 ('el', 289),
 ('elecciones', 290),
 ('elección', 291),
 ('electo', 292),
 ('eliminó', 293),
 ('elípticas', 294),
 ('embargo', 295),
 ('empieza', 296),
 ('empresas', 297),
 ('en', 298),
 ('encabezó', 299),
 ('encontraban', 300),
 ('encuentra', 301),
 ('encuentran', 302),
 ('encuesta', 303),
 ('enfrentar', 304),
 ('enormes', 305),
 ('entonces', 306),
 ('entre', 307),
 ('entró', 308),
 ('envuelto', 309),
 ('envés', 310),
 ('era', 311),
 ('es', 312),
 ('escapando', 313),
 ('ese', 314),
 ('espacial', 315),
 ('español', 316),
 ('especie', 317),
 ('esperando', 318),
 ('esta', 319),
 ('estabilización', 320),
 ('establecer', 321),
 ('establecimiento', 322),
 ('estables', 323),
 ('estación', 324),
 ('estado', 325),
 ('estados', 326),
 ('estadounidense', 327),
 ('estambres', 328),
 ('estas', 329),
 ('estatales', 330),
 ('estatización', 331),
 ('este', 332),
 ('estelares', 333),
 ('estimó', 334),
 ('estipuladas', 335),
 ('esto', 336),
 ('estrella', 337),
 ('estrujarlas', 338),
 ('estudios', 339),
 ('eufemística', 340),
 ('europa', 341),
 ('europeo', 342),
 ('evasión', 343),
 ('evento', 344),
 ('evidencia', 345),
 ('evitar', 346),
 ('evolucionó', 347),
 ('exigiendo', 348),
 ('existen', 349),
 ('existió', 350),
 ('expedida', 351),
 ('expresión', 352),
 ('extendiendo', 353),
 ('extendió', 354),
 ('externas', 355),
 ('familia', 356),
 ('fecha', 357),
 ('fertilización', 358),
 ('fin', 359),
 ('final', 360),
 ('finalmente', 361),
 ('financiando', 362),
 ('flor', 363),
 ('floración', 364),
 ('florece', 365),
 ('flores', 366),
 ('fonéticas', 367),
 ('forma', 368),
 ('forman', 369),
 ('formarse', 370),
 ('formas', 371),
 ('forzadas', 372),
 ('frecuentemente', 373),
 ('frei', 374),
 ('friedman', 375),
 ('frontera', 376),
 ('fruto', 377),
 ('frutos', 378),
 ('fue', 379),
 ('fuente', 380),
 ('fueran', 381),
 ('fuerte', 382),
 ('fuerza', 383),
 ('fuerzas', 384),
 ('fuese', 385),
 ('general', 386),
 ('generales', 387),
 ('generalmente', 388),
 ('global', 389),
 ('globoso', 390),
 ('gobernó', 391),
 ('gobierno', 392),
 ('golpe', 393),
 ('gran', 394),
 ('grande', 395),
 ('grandes', 396),
 ('graves', 397),
 ('griego', 398),
 ('gruesa', 399),
 ('gruesas', 400),
 ('grueso', 401),
 ('grupos', 402),
 ('guerra', 403),
 ('guillermo', 404),
 ('gustavo', 405),
 ('guzmán', 406),
 ('haber', 407),
 ('hablado', 408),
 ('habría', 409),
 ('habrían', 410),
 ('hace', 411),
 ('hacia', 412),
 ('hasta', 413),
 ('hay', 414),
 ('henry', 415),
 ('hermafroditas', 416),
 ('hibridaciones', 417),
 ('historiador', 418),
 ('histórico', 419),
 ('hoja', 420),
 ('hojas', 421),
 ('horizontalmente', 422),
 ('hoy', 423),
 ('humanidad', 424),
 ('humanos', 425),
 ('humedad', 426),
 ('hurtado', 427),
 ('húmedo', 428),
 ('ideal', 429),
 ('ideólogos', 430),
 ('ignición', 431),
 ('ilícitamente', 432),
 ('implementó', 433),
 ('impuestos', 434),
 ('in', 435),
 ('incluida', 436),
 ('incluso', 437),
 ('incrustadas', 438),
 ('indirecta', 439),
 ('industria', 440),
 ('inerme', 441),
 ('inflación', 442),
 ('inflorescencia', 443),
 ('influencia', 444),
 ('influida', 445),
 ('influyeron', 446),
 ('inga', 447),
 ('ingresaban', 448),
 ('ingresos', 449),
 ('inicia', 450),
 ('iniciada', 451),
 ('inicial', 452),
 ('inicio', 453),
 ('inmediata', 454),
 ('inmensidad', 455),
 ('innumerables', 456),
 ('insertadas', 457),
 ('instaló', 458),
 ('inteligencia', 459),
 ('intento', 460),
 ('intermedia', 461),
 ('internacional', 462),
 ('interno', 463),
 ('intervención', 464),
 ('interés', 465),
 ('introducido', 466),
 ('irán', 467),
 ('islámica', 468),
 ('izquierda', 469),
 ('izquierdistas', 470),
 ('jefe', 471),
 ('jorge', 472),
 ('josé', 473),
 ('juan', 474),
 ('juez', 475),
 ('jugo', 476),
 ('juicio', 477),
 ('junio', 478),
 ('junta', 479),
 ('junto', 480),
 ('justifican', 481),
 ('kab', 482),
 ('kaj', 483),
 ('kazajistán', 484),
 ('kissinger', 485),
 ('la', 486),
 ('larga', 487),
 ('largo', 488),
 ('las', 489),
 ('latina', 490),
 ('le', 491),
 ('legado', 492),
 ('legal', 493),
 ('leigh', 494),
 ('lenguajes', 495),
 ('liberado', 496),
 ('liberalización', 497),
 ('libertad', 498),
 ('libre', 499),
 ('liderada', 500),
 ('ligeramente', 501),
 ('limitó', 502),
 ('lingüistas', 503),
 ('liso', 504),
 ('llama', 505),
 ('llegando', 506),
 ('llevada', 507),
 ('llevado', 508),
 ('llevó', 509),
 ('lluvias', 510),
 ('lluviosa', 511),
 ('lo', 512),
 ('local', 513),
 ('lograron', 514),
 ('logre', 515),
 ('londres', 516),
 ('longitudinales', 517),
 ('los', 518),
 ('luego', 519),
 ('lunares', 520),
 ('luz', 521),
 ('madura', 522),
 ('maduran', 523),
 ('madurar', 524),
 ('magnesio', 525),
 ('magnéticos', 526),
 ('malus', 527),
 ('malvaceae', 528),
 ('malversación', 529),
 ('mandato', 530),
 ('mandos', 531),
 ('mantenía', 532),
 ('mantuvo', 533),
 ('manzana', 534),
 ('manzano', 535),
 ('maracas', 536),
 ('marcado', 537),
 ('margen', 538),
 ('marxista', 539),
 ('marzo', 540),
 ('masa', 541),
 ('maya', 542),
 ('mayor', 543),
 ('mayoría', 544),
 ('mazorca', 545),
 ('mañana', 546),
 ('mediano', 547),
 ('mediante', 548),
 ('medida', 549),
 ('medio', 550),
 ('medios', 551),
 ('mejor', 552),
 ('menos', 553),
 ('mercado', 554),
 ('merino', 555),
 ('meses', 556),
 ('metálicas', 557),
 ('mientras', 558),
 ('milagro', 559),
 ('miles', 560),
 ('milimétrica', 561),
 ('militar', 562),
 ('militares', 563),
 ('millones', 564),
 ('milton', 565),
 ('ministro', 566),
 ('misión', 567),
 ('mismo', 568),
 ('mm', 569),
 ('modo', 570),
 ('molinillo', 571),
 ('momento', 572),
 ('moneda', 573),
 ('monetaria', 574),
 ('monitorean', 575),
 ('montalva', 576),
 ('montañas', 577),
 ('motivos', 578),
 ('muerte', 579),
 ('mundo', 580),
 ('muñoz', 581),
 ('más', 582),
 ('médicamente', 583),
 ('médico', 584),
 ('nacido', 585),
 ('nacional', 586),
 ('nacionalización', 587),
 ('nación', 588),
 ('nativo', 589),
 ('nave', 590),
 ('necesarios', 591),
 ('necesita', 592),
 ('nitrógeno', 593),
 ('nixon', 594),
 ('no', 595),
 ('nombre', 596),
 ('normalmente', 597),
 ('noviembre', 598),
 ('nueva', 599),
 ('nuevo', 600),
 ('numerosas', 601),
 ('número', 602),
 ('oblonga', 603),
 ('oblongas', 604),
 ('obtusas', 605),
 ('obtuvo', 606),
 ('ocasionalmente', 607),
 ('octubre', 608),
 ('oeste', 609),
 ('operaciones', 610),
 ('oportunidades', 611),
 ('opositores', 612),
 ('optó', 613),
 ('orden', 614),
 ('orientación', 615),
 ('orientados', 616),
 ('origen', 617),
 ('oscuro', 618),
 ('otoño', 619),
 ('otro', 620),
 ('otros', 621),
 ('ovada', 622),
 ('ovaladas', 623),
 ('ovario', 624),
 ('palabra', 625),
 ('palacio', 626),
 ('paneles', 627),
 ('par', 628),
 ('para', 629),
 ('parece', 630),
 ('parte', 631),
 ('participaron', 632),
 ('participó', 633),
 ('partidarios', 634),
 ('partido', 635),
 ('partidos', 636),
 ('partir', 637),
 ('paso', 638),
 ('pasó', 639),
 ('patricio', 640),
 ('país', 641),
 ('pecioladas', 642),
 ('pecíolo', 643),
 ('pedro', 644),
 ('penales', 645),
 ('pendientes', 646),
 ('pequeña', 647),
 ('perenne', 648),
 ('perennes', 649),
 ('perennifolio', 650),
 ('periodo', 651),
 ('pero', 652),
 ('persiguió', 653),
 ('persistente', 654),
 ('personas', 655),
 ('período', 656),
 ('pesa', 657),
 ('pesar', 658),
 ('petróleo', 659),
 ('piel', 660),
 ('pinochet', 661),
 ('placas', 662),
 ('planearon', 663),
 ('planetas', 664),
 ('planificada', 665),
 ('planta', 666),
 ('platanero', 667),
 ('plebiscito', 668),
 ('poco', 669),
 ('poder', 670),
 ('polarización', 671),
 ('política', 672),
 ('políticas', 673),
 ('político', 674),
 ('políticos', 675),
 ('pomo', 676),
 ('poniendo', 677),
 ('popular', 678),
 ('por', 679),
 ('poroso', 680),
 ('posibilidad', 681),
 ('posición', 682),
 ('posteriormente', 683),
 ('potasio', 684),
 ('prats', 685),
 ('presidencia', 686),
 ('presidencial', 687),
 ('presidenciales', 688),
 ('presidente', 689),
 ('primarias', 690),
 ('primavera', 691),
 ('primer', 692),
 ('primera', 693),
 ('primero', 694),
 ('principal', 695),
 ('principio', 696),
 ('privatizó', 697),
 ('procesa', 698),
 ('produce', 699),
 ('produjeron', 700),
 ('produjo', 701),
 ('profundización', 702),
 ('prohibió', 703),
 ('promulgación', 704),
 ('pronunciamiento', 705),
 ('proponen', 706),
 ('protecciones', 707),
 ('protección', 708),
 ('provocar', 709),
 ('provocó', 710),
 ('proyectos', 711),
 ('pubescencia', 712),
 ('puede', 713),
 ('pulpa', 714),
 ('punta', 715),
 ('puntiaguda', 716),
 ('purpúrea', 717),
 ('purpúreo', 718),
 ('puso', 719),
 ('pétalos', 720),
 ('púrpura', 721),
 ('que', 722),
 ('quien', 723),
 ('racimos', 724),
 ('ramas', 725),
 ('ramificaciones', 726),
 ('ramillas', 727),
 ('ramón', 728),
 ('ratificado', 729),
 ('razón', 730),
 ('realizada', 731),
 ('realizado', 732),
 ('realizan', 733),
 ('realizarse', 734),
 ('rechazan', 735),
 ('recibe', 736),
 ('recolección', 737),
 ('recolectar', 738),
 ('recto', 739),
 ('redondeada', 740),
 ('redondeados', 741),
 ('reemplazo', 742),
 ('reforma', 743),
 ('reformas', 744),
 ('reformista', 745),
 ('refugió', 746),
 ('regiones', 747),
 ('región', 748),
 ('regresó', 749),
 ('reina', 750),
 ('relación', 751),
 ('rendir', 752),
 ('renuncia', 753),
 ('renunciado', 754),
 ('rené', 755),
 ('república', 756),
 ('requiere', 757),
 ('resistir', 758),
 ('restos', 759),
 ('resultado', 760),
 ('resultando', 761),
 ('revolución', 762),
 ('richard', 763),
 ('rico', 764),
 ('rojizo', 765),
 ('rojo', 766),
 ('romanos', 767),
 ('rosa', 768),
 ('rosáceas', 769),
 ('rápidamente', 770),
 ('régimen', 771),
 ('sabor', 772),
 ('salubridad', 773),
 ('salud', 774),
 ('salvador', 775),
 ('santiago', 776),
 ('satélite', 777),
 ('schneider', 778),
 ('se', 779),
 ('sebastián', 780),
 ('seca', 781),
 ('secretario', 782),
 ('sede', 783),
 ('segunda', 784),
 ('segundo', 785),
 ('seguridad', 786),
 ('según', 787),
 ('seis', 788),
 ('semillas', 789),
 ('senador', 790),
 ('septiembre', 791),
 ('ser', 792),
 ('shan', 793),
 ('si', 794),
 ('sido', 795),
 ('siempre', 796),
 ('siendo', 797),
 ('siglo', 798),
 ('significa', 799),
 ('sigue', 800),
 ('siguiente', 801),
 ('silvestre', 802),
 ('silvestres', 803),
 ('simple', 804),
 ('sin', 805),
 ('sindicatos', 806),
 ('sistemas', 807),
 ('sistemáticas', 808),
 ('sobre', 809),
 ('social', 810),
 ('socialismo', 811),
 ('socialista', 812),
 ('socialistas', 813),
 ('sociedad', 814),
 ('solares', 815),
 ('solo', 816),
 ('sombra', 817),
 ('son', 818),
 ('sostenga', 819),
 ('su', 820),
 ('sublevación', 821),
 ('subsecuente', 822),
 ('subtropicales', 823),
 ('sucesivamente', 824),
 ('suceso', 825),
 ('suele', 826),
 ('suelo', 827),
 ('sufrió', 828),
 ('suicidarse', 829),
 ('suicidó', 830),
 ('sumaron', 831),
 ('sumó', 832),
 ('supremo', 833),
 ('suprimieron', 834),
 ('sur', 835),
 ('sus', 836),
 ('sustituido', 837),
 ('sépalos', 838),
 ('talla', 839),
 ('tamaño', 840),
 ('también', 841),
 ('tanques', 842),
 ('tanquetazo', 843),
 ('tanto', 844),
 ('tapia', 845),
 ('temperatura', 846),
 ('tener', 847),
 ('teoría', 848),
 ('terminal', 849),
 ('terminales', 850),
 ('terminó', 851),
 ('terreno', 852),
 ('terrestre', 853),
 ('testa', 854),
 ('testimonio', 855),
 ('theobroma', 856),
 ('tian', 857),
 ('tiempo', 858),
 ('tiene', 859),
 ('tierras', 860),
 ('todo', 861),
 ('tomaban', 862),
 ('toribio', 863),
 ('tortura', 864),
 ('transformaciones', 865),
 ('tras', 866),
 ('través', 867),
 ('trayectoria', 868),
 ('treinta', 869),
 ('tres', 870),
 ('tronco', 871),
 ('tropas', 872),
 ('tropical', 873),
 ('tropicales', 874),
 ('tuvieron', 875),
 ('título', 876),
 ('ugarte', 877),
 ('umbeliforme', 878),
 ('un', 879),
 ('una', 880),
 ('unas', 881),
 ('unidad', 882),
 ('unidos', 883),
 ('universal', 884),
 ('universidad', 885),
 ('uña', 886),
 ('vacío', 887),
 ('valiosas', 888),
 ('valparaíso', 889),
 ('varias', 890),
 ('veinte', 891),
 ('verde', 892),
 ('verticilos', 893),
 ('veteados', 894),
 ('vez', 895),
 ('viejas', 896),
 ('viene', 897),
 ('viento', 898),
 ('vio', 899),
 ('violaciones', 900),
 ('virtud', 901),
 ('visita', 902),
 ('vitalicio', 903),
 ('vitaminas', 904),
 ('votos', 905),
 ('vuelve', 906),
 ('vía', 907),
 ('washington', 908),
 ('yucateco', 909),
 ('ápice', 910),
 ('árbol', 911),
 ('árboles', 912),
 ('áreas', 913),
 ('áspera', 914),
 ('ínfero', 915),
 ('órbita', 916)]

In [12]:
# Visualizando la matriz
bag_of_words_corpus.toarray()

array([[0, 2, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], shape=(6, 917))

In [13]:
print(len(bag_of_words_corpus.toarray()))
len(bag_of_words_corpus.toarray()[1])

6

917

In [16]:
import pandas as pd
def create_bow_dataframe(docs_raw: list, titles: list[str], vectorizer) -> pd.DataFrame:
    # fit_transform ajusta el vocabulario y crea la matriz en un solo paso
    matrix = vectorizer.fit_transform(docs_raw)

    # Podemos crear el DataFrame directamente pasando la matriz a un array tradicional
    # vectorizer.get_feature_names_out() nos da la lista de palabras en el orden exacto de las columnas
    df = pd.DataFrame(
        matrix.toarray(), index=titles, columns=vectorizer.get_feature_names_out()
    )
    return df

In [17]:
titles = ["ALLENDE", "PINOCHET", "GOLPE", "MANZANO", "CACAO", "ESPACIO"]
docs_matrix = create_bow_dataframe(
    documents,
    titles,
    vectorizer=CountVectorizer(tokenizer=simple_preprocess, token_pattern=None)#, binary=True),
)

In [18]:
docs_matrix

,abierta,abruptamente,acabó,acceder,accedió,acciones,acción,activamente,actualidad,actuar,...,vía,washington,yucateco,ápice,árbol,árboles,áreas,áspera,ínfero,órbita
ALLENDE,0,2,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
PINOCHET,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
GOLPE,0,0,0,0,1,2,2,2,0,1,...,0,1,0,0,0,0,0,0,0,0
MANZANO,1,0,0,0,0,0,0,0,1,0,...,0,0,0,1,2,0,0,0,1,0
CACAO,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,4,1,0,1,0,0
ESPACIO,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1

In [22]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

def compute_similarity_vectorized(docs_matrix):
    # Separate 'ESPACIO' from the rest of the dataframe
    espacio_df = docs_matrix.loc[['ESPACIO']]
    other_docs = docs_matrix.drop(index='ESPACIO')
    
    # compute similarities
    sims = cosine_similarity(other_docs, espacio_df).flatten()
    
    return pd.Series(sims, index=other_docs.index, name='Cosine Similarity vs ESPACIO').sort_values(ascending=False)

In [25]:
bow_simil = compute_similarity_vectorized(docs_matrix)
bow_simil

ALLENDE     0.765279
PINOCHET    0.752965
GOLPE       0.738800
CACAO       0.729573
MANZANO     0.722440
Name: Cosine Similarity vs ESPACIO, dtype: float64

#### TF-IDF

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
docs_matrix_tfidf = create_bow_dataframe(
    documents, titles, TfidfVectorizer(tokenizer=simple_preprocess, token_pattern=None)
)

In [21]:
docs_matrix_tfidf

,abierta,abruptamente,acabó,acceder,accedió,acciones,acción,activamente,actualidad,actuar,...,vía,washington,yucateco,ápice,árbol,árboles,áreas,áspera,ínfero,órbita
ALLENDE,0.000000,0.058401,0.023945,0.0292,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.023945,0.000000,0.000000,0.000000,0.000000,0.000000,0.0292,0.000000,0.000000,0.000000
PINOCHET,0.000000,0.000000,0.020363,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.020363,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000
GOLPE,0.000000,0.000000,0.000000,0.0000,0.028822,0.057643,0.057643,0.057643,0.000000,0.028822,...,0.000000,0.028822,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000
MANZANO,0.050485,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.050485,0.000000,...,0.000000,0.000000,0.000000,0.050485,0.069902,0.000000,0.0000,0.000000,0.050485,0.000000
CACAO,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.034866,0.000000,0.096553,0.034866,0.0000,0.034866,0.000000,0.000000
ESPACIO,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.055705,0.000000,0.0000,0.000000,0.000000,0.080462

In [26]:
tfidf_simil = compute_similarity_vectorized(docs_matrix_tfidf)
tfidf_simil

ALLENDE     0.537360
PINOCHET    0.517798
GOLPE       0.496077
CACAO       0.478602
MANZANO     0.438717
Name: Cosine Similarity vs ESPACIO, dtype: float64

#### 5. DataFrame

In [ ]:
comparison_df = pd.DataFrame({
    'BoW Similarity': bow_simil,
    'TF-IDF Similarity': tfidf_simil
})
comparison_df = comparison_df.sort_values(by='TF-IDF Similarity', ascending=False)
comparison_df

          BoW Similarity  TF-IDF Similarity
ALLENDE         0.765279           0.537360
PINOCHET        0.752965           0.517798
GOLPE           0.738800           0.496077
CACAO           0.729573           0.478602
MANZANO         0.722440           0.438717

#### 5.1. ¿Cambió el documento clasificado como "más similar/relevante" al pasar de BoW a TF-IDF? Identifica el cambio si lo hubo.

**Sí, el documento más relevante cambió.** Utilizando la representación **BoW**, el documento clasificado como más similar fue **ESPACIO**, ya que esta métrica se dejó engañar por la alta repetición de palabras clave. Sin embargo, al aplicar **TF-IDF**, el documento más relevante pasó a ser **ALLENDE**, reflejando una similitud semántica mucho más precisa.

#### 5.2. Explica brevemente, basándote en la penalización idf (Inverse Document Frequency), cómo y por qué TF-IDF procesó de manera distinta las palabras de tu "trampa léxica" en comparación con BoW.

En el modelo **BoW (Bag of Words)**, el peso de un término depende únicamente de cuántas veces aparece en el documento (frecuencia pura). Esto hace que el modelo sea vulnerable a "trampas léxicas", es decir, documentos que repiten artificialmente ciertas palabras muchas veces para inflar su vector y lograr engañar la métrica de similitud del coseno.

Por otro lado, **TF-IDF** introduce la métrica **IDF (Inverse Document Frequency)**, que funciona como un mecanismo de penalización o balanceo global. Si las palabras utilizadas en la trampa léxica aparecen en una gran cantidad de documentos dentro del corpus general, el mecanismo IDF asume que esas palabras no aportan información verdaderamente discriminatoria o única y reduce matemáticamente su peso (penalización). Al multiplicar la frecuencia del término (TF) por una penalización alta (IDF muy bajo), el peso final de esos términos artificiales colapsa. Esto permite que TF-IDF ignore el ruido de la repetición masiva e identifique el documento que genuinamente posee los términos distintivos y relevantes de la búsqueda.

## 2. Búsqueda de sesgos

In [ ]:
%pip install gensim

In [34]:
import gensim.downloader as gensim_api

word_vectors = gensim_api.load("glove-wiki-gigaword-100")

### 1.

In [35]:
print(word_vectors.most_similar(positive=['man', 'profession'], negative=['woman']))
print()
print(word_vectors.most_similar(positive=['woman', 'profession'], negative=['man']))

[('practice', 0.6156836152076721), ('knowledge', 0.6129590272903442), ('teaching', 0.5949095487594604), ('skill', 0.5886170864105225), ('reputation', 0.5880795121192932), ('philosophy', 0.5868663191795349), ('work', 0.5848589539527893), ('skills', 0.5772278904914856), ('discipline', 0.576593816280365), ('mind', 0.5739314556121826)]

[('professions', 0.6473134756088257), ('practitioner', 0.5966603755950928), ('nursing', 0.5942842364311218), ('vocation', 0.5698666572570801), ('teaching', 0.5623518824577332), ('childbirth', 0.543552815914154), ('academic', 0.5408717393875122), ('teacher', 0.5401057600975037), ('educator', 0.5207306742668152), ('qualifications', 0.5143449902534485)]

### 2. 
Podemos observar que los conceptos asociados con la mujer están más orientados a labores de enseñanza y cuidado, o meor dicho *crianza*, mientras que para los del hombre, se puede ver más un peso sobre la intelectualidad, el conocimiento y los hábitos, por lo que el sesgo es evidente.

### 3. 

En una analogía, podemos reutilizar la función para ver sesgos raciales.

In [36]:
print(word_vectors.most_similar(positive=['black', 'crime'], negative=['white']))
print()
print(word_vectors.most_similar(positive=['white', 'crime'], negative=['black']))

[('homicide', 0.6744564175605774), ('criminal', 0.6710113286972046), ('trafficking', 0.6675731539726257), ('crimes', 0.6656683087348938), ('murder', 0.6594251394271851), ('gang', 0.6294695138931274), ('gangs', 0.6266547441482544), ('criminals', 0.6202651858329773), ('theft', 0.6135585308074951), ('murders', 0.6067672371864319)]

[('criminal', 0.7276230454444885), ('crimes', 0.7032983303070068), ('terrorism', 0.6863258481025696), ('corruption', 0.6418624520301819), ('enforcement', 0.6342306733131409), ('fbi', 0.6149200797080994), ('investigation', 0.6137785911560059), ('prosecution', 0.5989775657653809), ('immigration', 0.5925841927528381), ('dealing', 0.5922744274139404)]

Mientras que, por un lado al asociar la palabra crimen con **negro**, se derivan conceptos con crímenes violentos y usuales en los reportes de criminalidad. Por el otro lado, al asociarlo con **blanco**, los conceptos son variados, entre crímenes de cuello blanco, como la corrupción así como conceptos que recaen más en el lado de la justicia.

### 4. Propuesta de modelo

Sabemos que, los modelos de lenguaje como los conocemos de hoy en día producen sesgos a partir de los datos con los que son entrenados, por lo que ciertos puntos a atender pueden ser los siguientes:
* Datasets más diversificados, con narrativas contrapuestas a partir de las características que pueden generar un sesgo.
* Ajuste de pesos a los vectores, si dichos pesos se ajustan a modo que se le reste importancia a las características que definen a un sesgo, se puede mejorar el resultado.
* Supervisión humana que pueda determinar si el entrenamiento del modelo produce sesgos y poder influir en la toma de decisiones.