## Práctica 3: Representaciones Vectoriales

**Fecha de entrega: 31 de Marzo de 2026 @ 11:59pm**

### Matrices dispersas y búsqueda de documentos

Este apartado requiere que construyas un motor de búsqueda entre documentos comparando el rendimiento de una Bolsa de Palabras (BoW) y TF-IDF para procesar un documento "tramposo" (documento con muchas palabras que aportan poco significado o valor temático):

Comenzamos el notebook importando las bibliotecas necesarias para el trabajo.

In [71]:
from pathlib import Path
import nltk
import numpy as np
import pandas as pd
import re
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import gensim.downloader as gensim_api

1. Define una lista de 5 documentos cortos divididos en dos temas contrastantes.
    - Ej: 3 de Revolución Rusa y 2 de comida vegana.
    
Comenzamos escribiendo los documentos, para ello utilicé la IA que redactara tres documentos que hablen de álgebra lineal y otros dos que hablen de dinosaurios con una longitud de al menos 300 palabras. 
Posteriormente, los obtenemos en nuestro código.

In [72]:
ruta_corpus = Path('./Documentos')
documentos = []
nombres_documentos = []
archivos = list(ruta_corpus.glob('algebra*.txt')) + list(ruta_corpus.glob('dinos*.txt'))

for archivo in archivos:
    with open(archivo, 'r', encoding='utf-8') as f:
        documentos.append(f.read())
        nombres_documentos.append(archivo.name)
print(documentos)
print(nombres_documentos)

['Definición de Espacio Vectorial\nUn espacio vectorial es una estructura algebraica abstracta que constituye el objeto de estudio fundamental del álgebra lineal.\nConceptualmente, se define como un conjunto de entidades matemáticas llamadas vectores, los cuales pueden sumarse entre sí y ser escalados (multiplicados) por números, conocidos como escalares, garantizando que el resultado de dichas operaciones siempre permanezca dentro del mismo conjunto.\nFormalmente, un espacio vectorial sobre un campo F (que generalmente representa a los números reales o a los números complejos) es un conjunto no vacío V equipado con dos operaciones principales:\nSuma de vectores: Una función que asocia a cada par de vectores u, v en V un único vector u + v que también pertenece a V (propiedad de cerradura bajo la suma).\nMultiplicación por un escalar: Una función que asocia a cada escalar c en F y a cada vector v en V un único vector cv que también pertenece a V (propiedad de cerradura bajo la multiplicación escalar).\nPara que el conjunto V sea estrictamente considerado un espacio vectorial, estas operaciones están obligadas a satisfacer rigurosamente los siguientes ocho axiomas para todos los vectores u, v, w en V y para todos los escalares a, b en F:\nConmutatividad de la suma: u + v = v + u\nAsociatividad de la suma: $(u + v) + w = u + (v + w)\nElemento neutro aditivo: Existe un vector único 0 en V tal que v + 0 = v\nInverso aditivo: Para cada vector v en V, existe un vector -v en V tal que v + -v = 0\nElemento neutro multiplicativo: $1v = v$ (donde 1 representa la identidad multiplicativa del campo F)\nAsociatividad de la multiplicación escalar: (ab)v = a(bv)\nDistributividad del escalar respecto a la suma vectorial: a(u + v) = au + av\nDistributividad del vector respecto a la suma escalar: (a + b)v = av + bv\nEl ejemplo clásico e intuitivo es el espacio euclidiano Rn utilizado para modelar el espacio geométrico y físico bidimensional o tridimensional.\nNo obstante, la potencia del álgebra lineal radica en su nivel de abstracción. \nLos "vectores" de un espacio vectorial no se limitan a ser representados como flechas con magnitud y dirección; también pueden ser polinomios, matrices bidimensionales, series de tiempo, funciones continuas o distribuciones de probabilidad, siempre y cuando el conjunto y sus operaciones respeten fielmente los ocho axiomas descritos.', 'La resolución de sistemas de ecuaciones lineales constituye una parte central de las matemáticas aplicadas.\nPara realizar un análisis riguroso de estos sistemas, es fundamental considerar la estructura de la matriz de coeficientes y los elementos del vector de constantes.\nEl objetivo principal es encontrar los valores de las incógnitas que satisfagan todas las ecuaciones simultáneamente.\nAl aplicar el método de eliminación de Gauss, buscamos desarrollar una secuencia de operaciones elementales por fila para obtener una matriz escalonada.\nDe esta forma, resulta mucho más sencillo encontrar la solución mediante un proceso de sustitución hacia atrás. \nEn muchos casos, el sistema puede presentar una única solución, infinitas soluciones o ninguna solución en absoluto.\nPara determinar en cuál de estos casos nos encontramos, debemos considerar el teorema de Rouché-Frobenius, el cual nos obliga a realizar una comparación analítica entre el rango de la matriz original y el rango de la matriz ampliada.\nSi ambos rangos coinciden, logramos obtener un sistema compatible; si difieren, la matriz va a presentar una inconsistencia insalvable. Como parte del proceso numérico, es crucial aplicar técnicas de pivoteo parcial o completo. \nAl realizar intercambios de filas para colocar los elementos de mayor magnitud en la diagonal principal, logramos desarrollar un algoritmo numéricamente estable, mitigando la acumulación de errores de redondeo.\nDe esta forma, los sistemas de software pueden obtener resultados precisos incluso cuando la matriz está mal condicionada.\nPresentar la solución final de forma paramétrica es necesario cuando el sistema es indeterminado, permitiendo así encontrar todo el espacio solución.\nSiempre se debe considerar que aplicar estos métodos ingenuamente consumirá muchos recursos, por lo que se deben desarrollar y presentar rutinas optimizadas para procesar cada parte y todos los elementos de forma rápida.', 'El análisis de valores y vectores propios es otra parte esencial del álgebra lineal, vital para desarrollar soluciones en sistemas dinámicos.\nAl realizar el estudio de una matriz cuadrada, buscamos encontrar aquellos vectores no nulos que, al aplicar la transformación lineal asociada, únicamente cambian su factor de escala.\nA estos elementos se les conoce como vectores propios, y al factor de escala que logramos obtener se le denomina valor propio.\nPara encontrar estos escalares, debemos considerar la ecuación característica y calcular las raíces del polinomio resultante.\nEn la mayoría de los casos, este proceso implica realizar el cálculo del determinante de una matriz modificada.\nAl obtener las raíces, la matriz puede presentar valores propios reales o complejos. Una vez que logramos encontrar todos los valores, podemos proceder a obtener los vectores propios correspondientes sustituyendo cada valor en el sistema original.\nEs importante considerar que un conjunto de vectores propios linealmente independientes puede presentar una base para todo el espacio. De esta forma, es factible desarrollar la diagonalización de la matriz, lo cual simplifica enormemente el cálculo de potencias matriciales.\nEn muchos casos de la física e ingeniería, aplicar la diagonalización permite desacoplar sistemas de ecuaciones diferenciales, aislando cada parte del problema para tratarla de forma individual.\nPor lo tanto, presentar una matriz en su forma diagonal es uno de los elementos más buscados por los analistas. Sin embargo, no siempre es posible realizar esta factorización; existen casos donde la matriz no es diagonalizable, obligando a los investigadores a desarrollar métodos alternativos y aplicar descomposiciones más complejas, como la descomposición en valores singulares, para poder obtener la información necesaria y presentar un modelo funcional con todos sus elementos intactos.', 'El estudio de los dinosaurios terópodos es una parte fascinante de la paleontología.\nPara realizar reconstrucciones precisas de estos formidables depredadores, los científicos deben considerar meticulosamente cada uno de los elementos óseos fosilizados.\nAl aplicar técnicas de datación radiométrica, los paleontólogos pueden obtener la edad aproximada de los estratos donde suelen encontrar estos restos.\nEn muchos casos, los cráneos de especies masivas como el Tyrannosaurus rex pueden presentar adaptaciones extremas para la caza. \nPor ejemplo, al desarrollar una mordida trituradora de huesos, podían aplicar fuerzas destructivas sobre sus presas. \nDe esta forma, lograban obtener acceso a nutrientes ricos como la médula ósea, una parte vital para mantener su enorme metabolismo acelerado. \nPara encontrar alimento de manera eficiente, debían realizar patrullajes constantes en su amplio territorio. \nEn ciertos casos, las evidencias geológicas sugieren que algunos terópodos más pequeños lograron desarrollar complejos comportamientos de caza en manada. \nEsto les permitía presentar una amenaza incluso para herbívoros de dimensiones mucho más grandes, al aplicar estrategias biológicas coordinadas para aislar a los elementos más débiles o jóvenes del rebaño.\nSiempre es fundamental considerar que la evolución no operaba de forma lineal; diversas familias de dinosaurios carnívoros lograron presentar adaptaciones únicas, como plumaje rudimentario, para obtener notables ventajas térmicas en climas fríos.\nAl realizar análisis biomecánicos en modernos modelos por computadora, los investigadores logran encontrar estimaciones precisas de su velocidad máxima y agilidad locomotora. \nCada nuevo fósil descubierto forma parte de un rompecabezas colosal, obligando a la comunidad científica a desarrollar nuevas teorías y considerar hipótesis audaces. \nEn la mayoría de los casos, presentar estos descubrimientos al público requiere simplificar el rigor científico de forma didáctica para poder obtener atención y aplicar nuevos fondos a la investigación de estos elementos.', 'La ecología de los dinosaurios herbívoros constituye una parte esencial para entender los ricos ecosistemas del Mesozoico.\nPara realizar estimaciones confiables sobre su dieta diaria, es necesario considerar la morfología de sus dientes y la robusta estructura de sus mandíbulas, elementos que solían presentar un desgaste extremo debido a la constante masticación de fibras. \nAl aplicar detallados estudios isotópicos en el esmalte dental petrificado, los biólogos evolutivos logran obtener datos sobre el tipo específico de vegetación que solían consumir.\nEn muchísimos casos, para poder obtener la inmensa cantidad de calorías necesarias para sobrevivir, estas enormes criaturas debían realizar prolongadas migraciones a nivel continental.\nDe esta forma, podían encontrar fuentes de abundante alimento fresco a medida que cambiaban las estaciones anuales. Al desarrollar defensas físicas pasivas como cuernos masivos, pesadas corazas osteodérmicas o colas en forma de mazo destructivo, múltiples especies lograban presentar una barrera formidable contra los depredadores más grandes.\nEn caso de ataque directo, podían aplicar golpes contundentes de forma letal para defenderse. Es sumamente interesante considerar que, en la mayoría de los casos, el comportamiento gregario fue la parte fundamental de su éxito de supervivencia.\nAl moverse en manadas compuestas por cientos de individuos, lograban presentar un denso frente unido, dificultando significativamente que los carnívoros solitarios pudieran encontrar e aislar a los elementos enfermos o recién nacidos. \nPara desarrollar un ecosistema prehistórico equilibrado, se necesitaba una vasta biodiversidad de flora continental, la cual también tuvo que realizar agresivas adaptaciones evolutivas para soportar el constante ramoneo. \nAl encontrar amplios yacimientos de nidos fosilizados, la ciencia ha podido obtener pruebas innegables de que muchos dinosaurios herbívoros lograron desarrollar complejos y tiernos cuidados parentales, asegurando así la supervivencia de sus vulnerables crías de forma activa e inteligente.']
['algebra_espacios.txt', 'algebra_sistemas.txt', 'algebra_valores_propios.txt', 'dinos_carnivoros.txt', 'dinos_herbivoros.txt']


2. Crea una query "tramposa", esto es, crea un documento dirigido a alguna temática pero repitiendo intencionalmente palabras comunes o verbos genéricos que aparezcan en los documentos de la otra temática.

Creamos una query con la temática de un cuento de dinosaurios explicando el concepto de espacio vectorial, de esta manera, tenemos un documento que habla de los espacios vectoriales pero incluye multiples veces terminos de dinosaurios. Para ello, pedi a la IA que redactara un cuento de dinosaurios que explica los espacios vectoriales como si fuera una historia con dinosaurios.

In [73]:
with open('./Documentos/trampa.txt', 'r', encoding='utf-8') as f:
    texto_query = f.read()

query = [texto_query]

print(query)

['Había una vez, en un valle prehistórico que parecía una verdadera estructura algebraica abstracta, dos dinosaurios muy distintos: Vector, un Velociraptor de plumaje rudimentario, y Escalar, una enorme Branquiosaurio que debía realizar prolongadas migraciones para encontrar alimento fresco. Aunque uno era un depredador y la otra una herbívora, ambos consideraban que el movimiento era el objeto de estudio fundamental de su mundo.\nUn día, decidieron presentar sus ideas frente a un gran lago de lodo seco.\n—Mira, Escalar —dijo Vector—. Para definir mi posición y obtener mi presa, necesito dos cosas: una dirección y una magnitud. A eso lo llamo un vector, y nosotros somos las entidades matemáticas de este valle.\nEscalar asintió, mientras masticaba fibras vegetales.\n—Y yo soy el escalar. Yo no tengo dirección, formo parte de un campo F, como los números reales. Solo soy un número que puede aplicar una fuerza para estirar o encoger tus saltos. Si te digo que saltes "2", duplicas tu longitud.\nVector trazó una línea en el lodo cerca de unos nidos fosilizados para desarrollar su teoría.\n—Pero aquí viene lo importante: este valle es un Espacio Vectorial. Para que lo sea en todos los casos, debemos considerar y respetar rigurosamente ciertos axiomas.\nVector dio un salto hacia el norte (u) y luego uno hacia el este (v).\n—Al realizar la suma de mis dos movimientos, logro obtener un nuevo camino que todavía está dentro de nuestro valle. A esto se le llama propiedad de cerradura bajo la suma. Nunca apareceré mágicamente en otra dimensión, siempre seré parte de este mismo conjunto.\nEscalar señaló una piedra con evidencias geológicas para presentar otro punto.\n—Debe existir un salto que no te mueva a ninguna parte, el elemento neutro aditivo. Si te quedas quieto, sumas el vector 0 y te mantienes donde estás. Sin un origen, no hay orden.\n—Y si salto hacia adelante para atacar —añadió Vector—, siempre debe existir un salto igual pero en dirección opuesta, mi inverso aditivo (-u), que me devuelva al inicio de forma exacta.\nEscalar explicó que, al aplicar la distributividad del escalar respecto a la suma vectorial, si ella multiplicaba una suma de saltos de Vector, era lo mismo que multiplicar cada uno por separado. Las leyes de la multiplicación escalar eran tan precisas como la fuerza destructiva de una mordida.\nAl final del día, comprendieron que un Espacio Vectorial no es solo flechas y números, sino un alto nivel de abstracción donde los elementos siguen reglas perfectas. Desde entonces, los dinosaurios ya no solo corrían por instinto, sino que se desplazaban con la elegancia de una combinación lineal, logrando encontrar que incluso los polinomios o las matrices bidimensionales podían comportarse de esta forma en su ecosistema, formando parte de ese rompecabezas colosal que es el álgebra lineal.']


3. Vectoriza para crear una BoW y calcula la similitud coseno entre la query y los 5 documentos

Reciclamos el codigo de la clase para vectorizar y crear la BoW correspondiente a los documentos que creamos.

In [74]:
def simple_preprocess(text: str):
    tokens = word_tokenize(text.lower(), language="spanish")
    # Ignoramos signos de puntuación y palabras de longitud 1
    return [word for word in tokens if word.isalnum() and len(word) > 1 and not re.match(r"\d+", word)]

In [75]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ianar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [76]:
vectorizer = CountVectorizer(tokenizer=simple_preprocess, token_pattern=None)
bag_of_words_corpus = vectorizer.fit_transform(documentos)
diccionario = vectorizer.vocabulary_
sorted(diccionario.items(), key=lambda x: x[1])
for column_idx, word in enumerate(vectorizer.get_feature_names_out()):
    print(column_idx, word)

0 ab
1 absoluto
2 abstracción
3 abstracta
4 abundante
5 acceso
6 acelerado
7 activa
8 acumulación
9 adaptaciones
10 aditivo
11 agilidad
12 agresivas
13 aislando
14 aislar
15 al
16 algebraica
17 algoritmo
18 algunos
19 alimento
20 alternativos
21 ambos
22 amenaza
23 ampliada
24 amplio
25 amplios
26 analistas
27 analítica
28 anuales
29 análisis
30 aplicadas
31 aplicar
32 aproximada
33 aquellos
34 asegurando
35 asocia
36 asociada
37 asociatividad
38 así
39 ataque
40 atención
41 atrás
42 au
43 audaces
44 av
45 axiomas
46 bajo
47 barrera
48 base
49 bidimensional
50 bidimensionales
51 biodiversidad
52 biológicas
53 biomecánicos
54 biólogos
55 buscados
56 buscamos
57 bv
58 cada
59 calcular
60 calorías
61 cambiaban
62 cambian
63 campo
64 cantidad
65 característica
66 carnívoros
67 caso
68 casos
69 caza
70 central
71 cerradura
72 ciencia
73 cientos
74 científica
75 científico
76 científicos
77 ciertos
78 climas
79 clásico
80 coeficientes
81 coinciden
82 colas
83 colocar
84 colosal
85 como
86 comparación
87 compatible
88 complejas
89 complejos
90 completo
91 comportamiento
92 comportamientos
93 compuestas
94 computadora
95 comunidad
96 con
97 conceptualmente
98 condicionada
99 confiables
100 conjunto
101 conmutatividad
102 conoce
103 conocidos
104 considerado
105 considerar
106 constante
107 constantes
108 constituye
109 consumir
110 consumirá
111 continental
112 continuas
113 contra
114 contundentes
115 coordinadas
116 corazas
117 correspondientes
118 criaturas
119 crucial
120 cráneos
121 crías
122 cuadrada
123 cual
124 cuales
125 cuando
126 cuernos
127 cuidados
128 cuál
129 cv
130 cálculo
131 datación
132 datos
133 de
134 debe
135 debemos
136 deben
137 debido
138 debían
139 defenderse
140 defensas
141 define
142 definición
143 del
144 denomina
145 denso
146 dental
147 dentro
148 depredadores
149 desacoplar
150 desarrollar
151 descomposiciones
152 descomposición
153 descritos
154 descubierto
155 descubrimientos
156 desgaste
157 destructivas
158 destructivo
159 detallados
160 determinante
161 determinar
162 diagonal
163 diagonalizable
164 diagonalización
165 diaria
166 dichas
167 didáctica
168 dientes
169 dieta
170 diferenciales
171 dificultando
172 difieren
173 dimensiones
174 dinosaurios
175 dinámicos
176 dirección
177 directo
178 distribuciones
179 distributividad
180 diversas
181 donde
182 dos
183 débiles
184 ecología
185 ecosistema
186 ecosistemas
187 ecuaciones
188 ecuación
189 edad
190 eficiente
191 ejemplo
192 el
193 elementales
194 elemento
195 elementos
196 eliminación
197 embargo
198 en
199 encontramos
200 encontrar
201 enfermos
202 enorme
203 enormemente
204 enormes
205 entender
206 entidades
207 entre
208 equilibrado
209 equipado
210 errores
211 es
212 escala
213 escalados
214 escalar
215 escalares
216 escalonada
217 esencial
218 esmalte
219 espacio
220 especies
221 específico
222 esta
223 estable
224 estaciones
225 estas
226 este
227 estimaciones
228 esto
229 estos
230 estrategias
231 estratos
232 estrictamente
233 estructura
234 estudio
235 estudios
236 está
237 están
238 euclidiano
239 evidencias
240 evolución
241 evolutivas
242 evolutivos
243 existe
244 existen
245 extremas
246 extremo
247 factible
248 factor
249 factorización
250 familias
251 fascinante
252 fibras
253 fielmente
254 fila
255 filas
256 final
257 flechas
258 flora
259 fondos
260 forma
261 formalmente
262 formidable
263 formidables
264 fosilizados
265 frente
266 fresco
267 fríos
268 fue
269 fuentes
270 fuerzas
271 funcional
272 funciones
273 función
274 fundamental
275 física
276 físicas
277 físico
278 fósil
279 garantizando
280 gauss
281 generalmente
282 geológicas
283 geométrico
284 golpes
285 grandes
286 gregario
287 ha
288 hacia
289 herbívoros
290 hipótesis
291 huesos
292 identidad
293 implica
294 importante
295 incluso
296 inconsistencia
297 incógnitas
298 independientes
299 indeterminado
300 individual
301 individuos
302 infinitas
303 información
304 ingeniería
305 ingenuamente
306 inmensa
307 innegables
308 insalvable
309 intactos
310 inteligente
311 intercambios
312 interesante
313 intuitivo
314 inverso
315 investigación
316 investigadores
317 isotópicos
318 jóvenes
319 la
320 las
321 le
322 les
323 letal
324 limitan
325 lineal
326 lineales
327 linealmente
328 llamadas
329 lo
330 locomotora
331 lograban
332 logramos
333 logran
334 lograron
335 los
336 magnitud
337 mal
338 manada
339 manadas
340 mandíbulas
341 manera
342 mantener
343 masivas
344 masivos
345 masticación
346 matemáticas
347 matrices
348 matriciales
349 matriz
350 mayor
351 mayoría
352 mazo
353 mediante
354 medida
355 mesozoico
356 metabolismo
357 meticulosamente
358 migraciones
359 mismo
360 mitigando
361 modelar
362 modelo
363 modelos
364 modernos
365 modificada
366 mordida
367 morfología
368 moverse
369 mucho
370 muchos
371 muchísimos
372 multiplicación
373 multiplicados
374 multiplicativa
375 multiplicativo
376 más
377 máxima
378 médula
379 método
380 métodos
381 múltiples
382 nacidos
383 necesaria
384 necesarias
385 necesario
386 necesitaba
387 neutro
388 nidos
389 ninguna
390 nivel
391 no
392 nos
393 notables
394 nuevas
395 nuevo
396 nuevos
397 nulos
398 numéricamente
399 numérico
400 nutrientes
401 números
402 objetivo
403 objeto
404 obliga
405 obligadas
406 obligando
407 obstante
408 obtener
409 ocho
410 operaba
411 operaciones
412 optimizadas
413 original
414 osteodérmicas
415 otra
416 paleontología
417 paleontólogos
418 par
419 para
420 paramétrica
421 parcial
422 parentales
423 parte
424 pasivas
425 patrullajes
426 pequeños
427 permanezca
428 permite
429 permitiendo
430 permitía
431 pertenece
432 pesadas
433 petrificado
434 pivoteo
435 plumaje
436 podemos
437 poder
438 podido
439 podían
440 polinomio
441 polinomios
442 por
443 posible
444 potencia
445 potencias
446 precisas
447 precisos
448 prehistórico
449 presas
450 presentar
451 principal
452 principales
453 probabilidad
454 problema
455 proceder
456 procesar
457 proceso
458 prolongadas
459 propiedad
460 propio
461 propios
462 pruebas
463 pudieran
464 puede
465 pueden
466 público
467 que
468 radica
469 radiométrica
470 ramoneo
471 rango
472 rangos
473 raíces
474 reales
475 realizar
476 rebaño
477 recién
478 reconstrucciones
479 recursos
480 redondeo
481 representa
482 representados
483 requiere
484 resolución
485 respecto
486 respeten
487 restos
488 resulta
489 resultado
490 resultados
491 resultante
492 rex
493 ricos
494 rigor
495 rigurosamente
496 riguroso
497 rn
498 robusta
499 rompecabezas
500 rudimentario
501 rutinas
502 rápida
503 satisfacer
504 satisfagan
505 se
506 sea
507 secuencia
508 sencillo
509 ser
510 series
511 si
512 siempre
513 significativamente
514 siguientes
515 simplifica
516 simplificar
517 simultáneamente
518 sin
519 singulares
520 sistema
521 sistemas
522 sobre
523 sobrevivir
524 software
525 solitarios
526 soluciones
527 solución
528 solían
529 soportar
530 su
531 suelen
532 sugieren
533 suma
534 sumamente
535 sumarse
536 supervivencia
537 sus
538 sustitución
539 sustituyendo
540 sí
541 tal
542 también
543 tanto
544 teorema
545 teorías
546 territorio
547 terópodos
548 tiempo
549 tiernos
550 tipo
551 todas
552 todo
553 todos
554 transformación
555 tratarla
556 tridimensional
557 trituradora
558 tuvo
559 tyrannosaurus
560 técnicas
561 térmicas
562 un
563 una
564 unido
565 uno
566 utilizado
567 va
568 vacío
569 valor
570 valores
571 vasta
572 vector
573 vectores
574 vectorial
575 vegetación
576 velocidad
577 ventajas
578 vez
579 vital
580 vulnerables
581 yacimientos
582 álgebra
583 éxito
584 ósea
585 óseos
586 única
587 únicamente
588 únicas
589 único

Obtenemos una lista de palabras ordenada por índice de columna, que es el mismo orden que las columnas de la matriz de bag of words. Esto nos permite interpretar cada columna de la matriz como la frecuencia de una palabra específica en cada documento. De esta manera podemos visualizar la BoW como una matriz cuyas filas corresponden a la frecuencia de las palabras en cada uno de los documentos.

In [77]:
    # Visualizando la matriz
bag_of_words_corpus.toarray()

array([[1, 0, 1, ..., 0, 0, 3],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5, 590))

Finalmente utilizando la función de la clase creamos un dataframe de pandas para visualizar de manera más comoda la información.

In [78]:
def create_bow_dataframe(docs_raw: list, titles: list[str], vectorizer) -> pd.DataFrame:
    # fit_transform ajusta el vocabulario y crea la matriz en un solo paso
    matrix = vectorizer.fit_transform(docs_raw)

    # Podemos crear el DataFrame directamente pasando la matriz a un array tradicional
    # vectorizer.get_feature_names_out() nos da la lista de palabras en el orden exacto de las columnas
    df = pd.DataFrame(
        matrix.toarray(), index=titles, columns=vectorizer.get_feature_names_out()
    )
    return df

In [79]:
titles = ["ESPACIOS", "SISTEMAS", "VALORES_PROPIOS", "CARNIVOROS", "HERBIVOROS", "TRAMPAS" ]
docs_matrix = create_bow_dataframe(
    documentos + query,
    titles,
    vectorizer=CountVectorizer(tokenizer=simple_preprocess, token_pattern=None)#, binary=True),
)

In [80]:
docs_matrix

,ab,absoluto,abstracción,abstracta,abundante,acceso,acelerado,activa,acumulación,adaptaciones,...,yacimientos,yo,álgebra,éxito,ósea,óseos,única,únicamente,únicas,único
ESPACIOS,1,0,1,1,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,3
SISTEMAS,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
VALORES_PROPIOS,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
CARNIVOROS,0,0,0,0,0,1,1,0,0,2,...,0,0,0,0,1,1,0,0,1,0
HERBIVOROS,0,0,0,0,1,0,0,1,0,1,...,1,0,0,1,0,0,0,0,0,0
TRAMPAS,0,0,1,1,0,0,0,0,0,0,...,0,2,1,0,0,0,0,0,0,0

Ahora, calculamos la similitud coseno entre la query y los cinco documentos.

In [81]:
query_vector = docs_matrix.loc["TRAMPAS"].values.reshape(1, -1)
cos_similarity_bow = []
for doc_title in titles[:-1]:
    current_doc_values = docs_matrix.loc[doc_title].values.reshape(1, -1)
    similarity = cosine_similarity(query_vector, current_doc_values)[0][0]
    cos_similarity_bow.append(similarity)
    print(f"Similitud entre 'TRAMPAS' y '{doc_title}': {similarity:.4f}")

Similitud entre 'TRAMPAS' y 'ESPACIOS': 0.7501
Similitud entre 'TRAMPAS' y 'SISTEMAS': 0.6676
Similitud entre 'TRAMPAS' y 'VALORES_PROPIOS': 0.6294
Similitud entre 'TRAMPAS' y 'CARNIVOROS': 0.6113
Similitud entre 'TRAMPAS' y 'HERBIVOROS': 0.6657


4. Repite el proceso usando TF-IDF

Obtenemos de manera similar al ejercicio anterior el dataframe de los vectores de la BoW usando TF-IDF cambiando el vectorizador por uno del tipo Tfidf.

In [82]:
docs_matrix_tfidf = create_bow_dataframe(
    documentos + query,
    titles,
    vectorizer=TfidfVectorizer(tokenizer=simple_preprocess, token_pattern=None)
)
docs_matrix_tfidf

,ab,absoluto,abstracción,abstracta,abundante,acceso,acelerado,activa,acumulación,adaptaciones,...,yacimientos,yo,álgebra,éxito,ósea,óseos,única,únicamente,únicas,único
ESPACIOS,0.043983,0.000000,0.036067,0.036067,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.00000,0.00000,0.060900,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.131949
SISTEMAS,0.000000,0.048527,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.048527,0.000000,...,0.00000,0.00000,0.000000,0.00000,0.000000,0.000000,0.048527,0.00000,0.000000,0.000000
VALORES_PROPIOS,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.00000,0.00000,0.037308,0.00000,0.000000,0.000000,0.000000,0.05389,0.000000,0.000000
CARNIVOROS,0.000000,0.000000,0.000000,0.000000,0.00000,0.055722,0.055722,0.00000,0.000000,0.091386,...,0.00000,0.00000,0.000000,0.00000,0.055722,0.055722,0.000000,0.00000,0.055722,0.000000
HERBIVOROS,0.000000,0.000000,0.000000,0.000000,0.05508,0.000000,0.000000,0.05508,0.000000,0.045167,...,0.05508,0.00000,0.000000,0.05508,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
TRAMPAS,0.000000,0.000000,0.031054,0.031054,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.00000,0.07574,0.026218,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000

Y luego calculamos la diferencia coseno entre la query y los cinco documentos:

In [83]:
query_vector = docs_matrix_tfidf.loc["TRAMPAS"].values.reshape(1, -1)
cos_similarity_tfidf = []
for doc_title in titles[:-1]:  
    current_doc_values = docs_matrix_tfidf.loc[doc_title].values.reshape(1, -1)
    similarity = cosine_similarity(query_vector, current_doc_values)[0][0]
    cos_similarity_tfidf.append(similarity)
    print(f"Similitud entre 'TRAMPAS' y '{doc_title}': {similarity:.4f}")

Similitud entre 'TRAMPAS' y 'ESPACIOS': 0.5542
Similitud entre 'TRAMPAS' y 'SISTEMAS': 0.4325
Similitud entre 'TRAMPAS' y 'VALORES_PROPIOS': 0.3864
Similitud entre 'TRAMPAS' y 'CARNIVOROS': 0.3954
Similitud entre 'TRAMPAS' y 'HERBIVOROS': 0.4093

5. Imprime un DataFrame o tabla comparativa que muestre los scores de similitud de BoW y TF-IDF del query contra los 5 documentos.

Obtenemos el dataframe.

In [84]:
df_comparativo = pd.DataFrame({
    'Documento': nombres_documentos,
    'Score BoW': cos_similarity_bow,
    'Score TF-IDF': cos_similarity_tfidf
})
df_comparativo

                     Documento  Score BoW  Score TF-IDF
0         algebra_espacios.txt   0.750126      0.554185
1         algebra_sistemas.txt   0.667618      0.432525
2  algebra_valores_propios.txt   0.629371      0.386446
3         dinos_carnivoros.txt   0.611269      0.395372
4         dinos_herbivoros.txt   0.665698      0.409320

- ¿Cambió el documento clasificado como "más similar/relevante" al pasar de BoW a TF-IDF? Identifica el cambio si lo hubo.

    Podemos ver que en la BoW sin tf-idf el documento más cercano a la query tramposa de dinosaurios hablando de espacios vectoriales es el documento que habla de espacios vectoriales, sin embargo, tambien tiene muchisima relación el texto que habla de dinosaurios herbivoros y carnivoros dado que en la query tramposamente agregamos palabras que se relacionan a los dinosaurios. En un modelo en el que buscamos caracterizar los documentos la tematica de nuestra trampa no deberia de ser acerca de los dinosaurios herbívoros pues es claro que el tema central son las características de un espacio vectorial.

    Ahora bien, con respecto a la matriz con TF-IDF tenemos que los documentos más cercanos a la query tramposa en realidad son los que hablan de algebra lineal y los documentos de dinosaurios pierden muchisima relación con la query. Este resultado es ideal, pues es claro que en nuestra query el tema que caracteriza el documento trampa es el algebra lineal por lo que debería perder relevancia el tema de los dinosaurios.

- Explica brevemente, basándote en la penalización idf (Inverse Document Frequency), cómo y por qué TF-IDF procesó de manera distinta las palabras de tu "trampa léxica" en comparación con BoW.

    Dado que la BoW se basa en contar frecuencias, como la query trampa metia terminos relacionados a los dinosaurios herbivoros y carnívoros aumentó la frecuencia de dichos términos lo que infló su similitud con los documentos de dinosaurios poniendolo como tema central del texto aunque no lo fuera.
    Por otro lado, cuando utilizamos TF-IDF la penalización idf le agregó mas peso a las palabras frecuentes en el documento pero no tan frecuentes en los demás. Por ello, palabras como vector, escalar o neutro que aparecen en la query y en especifico en el documento que define los espacios vectoriales tienen mayor peso comparado con palabras como dinosaurio o algunos verbos genéricos que aparecen tanto en el documento de dinosaurios herbívoros y carnívoros o en general en los cinco documentos.

### Búsqueda de sesgos

1. Descarga el modelo `glove-wiki-gigaword-100` con la api de `gensim` y ejecuta el siguiente código:

```python
print(word_vectors.most_similar(positive=['man', 'profession'], negative=['woman']))
print()
print(word_vectors.most_similar(positive=['woman', 'profession'], negative=['man']))
```

In [85]:
word_vectors = gensim_api.load("glove-wiki-gigaword-100")
print(word_vectors.most_similar(positive=['man', 'profession'], negative=['woman']))
print()
print(word_vectors.most_similar(positive=['woman', 'profession'], negative=['man']))

[('practice', 0.6156836152076721), ('knowledge', 0.6129590272903442), ('teaching', 0.5949095487594604), ('skill', 0.5886170864105225), ('reputation', 0.588079571723938), ('philosophy', 0.5868663191795349), ('work', 0.5848589539527893), ('skills', 0.5772278904914856), ('discipline', 0.576593816280365), ('mind', 0.5739315152168274)]

[('professions', 0.6473134756088257), ('practitioner', 0.5966603755950928), ('nursing', 0.5942842364311218), ('vocation', 0.5698666572570801), ('teaching', 0.5623518824577332), ('childbirth', 0.543552815914154), ('academic', 0.5408717393875122), ('teacher', 0.5401058197021484), ('educator', 0.5207306742668152), ('qualifications', 0.5143449902534485)]


2. Identifica las diferencias en la lista de palabras asociadas a hombres/mujeres y profesiones, explica como esto reflejaría un sesgo de genero.

A pesar de que en ambos casos aparecen términos vinculados al ámbito profesional (como professions, practitioner o practice), es evidente un sesgo de género marcado. Mientras que a los hombres se les vincula con el trabajo, las habilidades técnicas y el conocimiento aplicado, a las mujeres se las asocia predominantemente con la enfermería o la enseñanza. Me causa mucho ruido que el término "embarazo" aparezca en esta relación.

Este fenómeno refleja los roles de género presentes en los corpus de entrenamiento. Históricamente, muchos textos describen al hombre bajo el rol de proveedor, orientándolo al desarrollo de capacidades profesionales, mientras que a menudo se subestima la competencia femenina o se la posiciona como una opción menos favorable. Esto explica por qué las palabras referentes a habilidades técnicas no muestran una similitud vectorial con "mujer" y "profesión". Además, persiste la idea errónea de que las profesiones "naturales" para las mujeres son aquellas relacionadas con el cuidado y la educación, lo que mete a la lista de resultados con términos como enfermera, educadora o maestra.

Asimismo, es alarmante encontrar la palabra "parto" asociada a la mujer en un contexto profesional. Esto es, probablemente, un reflejo de la discriminación estructural: en puestos de alta jerarquía y remuneración, se suele penalizar la posibilidad de la maternidad. Los empleadores —en su mayoría hombres— suelen percibir el embarazo y sus secuelas como un factor de "poca confiabilidad" o una potencial pérdida de productividad. En consecuencia, el embarazo y el parto adquieren una relevancia desproporcionada en el desarrollo profesional de las mujeres, convirtiéndose en un factor de exclusión que, lógicamente, no afecta la trayectoria de los hombres.


3. Utiliza la función `.most_similar()` para identificar analogías que exhiba algún tipo de sesgo de los vectores pre-entrenados.
    - Explica brevemente que sesgo identificar
    Podemos ver que la relación entre personas mexicanas, o en general de cualquier país formado, se relaciona con progreso económico basado en capital

In [86]:
print(word_vectors.most_similar(positive=['american', 'migration'], negative=['mexican']))
print(word_vectors.most_similar(positive=['american', 'immigration'], negative=['mexican']))
print()
print(word_vectors.most_similar(positive=['mexican', 'migration'], negative=['american']))
print(word_vectors.most_similar(positive=['mexican', 'immigration'], negative=['american']))

[('migrations', 0.5379707217216492), ('research', 0.5363138914108276), ('emigration', 0.5281015634536743), ('evolution', 0.5277126431465149), ('society', 0.5195993781089783), ('europe', 0.5114848613739014), ('study', 0.5078940987586975), ('development', 0.5071896314620972), ('expansion', 0.5032796263694763), ('integration', 0.49866756796836853)]
[('britain', 0.611629843711853), ('policy', 0.6086573600769043), ('law', 0.5825565457344055), ('liberties', 0.5784686207771301), ('united', 0.5731073021888733), ('legal', 0.566255509853363), ('washington', 0.5661957263946533), ('issue', 0.5601418018341064), ('states', 0.5596628785133362), ('issues', 0.5570847392082214)]

[('migrant', 0.5767035484313965), ('migrants', 0.5573159456253052), ('emigration', 0.5392107367515564), ('trafficking', 0.4975281357765198), ('migrations', 0.4881719946861267), ('immigration', 0.4773959219455719), ('immigrants', 0.47451457381248474), ('undocumented', 0.4721716642379761), ('migratory', 0.4701482951641083), ('urbanization', 0.4669433832168579)]
[('immigrants', 0.572886049747467), ('enforcement', 0.5486474633216858), ('naturalization', 0.5402010679244995), ('mexico', 0.5348947048187256), ('trafficking', 0.5313142538070679), ('undocumented', 0.5296998023986816), ('puerto', 0.5287684798240662), ('migrant', 0.5174103379249573), ('immigrant', 0.5153382420539856), ('illegal', 0.5071293711662292)]

Podemos observar que, dado que muchos de estos modelos se entrenan principalmente con datos generados en Estados Unidos, tienden a incorporar los sesgos presentes en el discurso social y mediático de ese contexto. En particular, esto se refleja en la forma en que se representa el fenómeno de la migración. Por un lado, la inmigración hacia ese país por parte de paises como mexico suele asociarse con connotaciones negativas, vinculándose frecuentemente con la ilegalidad, la criminalidad o actividades como el tráfico de drogas. Por otro lado, la migración desde ese pais se relaciona con ideas positivas como el desarrollo, la expansión de oportunidades o el acceso a la educación.

Esta diferencia en las asociaciones no es casual, sino que responde a narrativas predominantes que posicionan la inmigración como un problema interno que debe ser gestionado o controlado, mientras que la movilidad humana de grupos privilegiados se interpretan como procesos legítimos o incluso deseables. Como consecuencia, los modelos no solo reproducen estas diferencias, sino que pueden reforzarlas al presentarlas como relaciones naturales.


4. Si fuera tu trabajo crear un modelo ¿Como mitigarías estos sesgos al crear vectores de palabras?

Considero que el problema del sesgo en estos sistemas no radica únicamente en su funcionamiento técnico, sino que es, una consecuencia de los sesgos sociales, culturales y de género presentes en nuestras sociedades. Dado que estos modelos se entrenan con grandes volúmenes de texto, y que históricamente la producción escrita ha estado dominada por hombres en posiciones de privilegio, existe una sobrerrepresentación de sus perspectivas frente a las de poblaciones vulnerables. Como resultado, el sistema tiende a aprender y reproducir estas visiones como si fueran neutrales o universales, reflejándolas en sus respuestas.

Para solucionarlo creo que se debe fomentar y facilitar el acceso a la expresión y producción de conocimiento por parte de estas poblaciones. Sin embargo, sabemos que reducir las desigualdades estructurales que limitan dicha participación es una tarea compleja y de largo plazo, por ello, una medida inmediata sería incorporar de manera deliberada literatura y contenidos que representen las experiencias, visiones del mundo y problemáticas de estos grupos, así como textos críticos que evidencien las desigualdades generadas por los sesgos existentes. Asimismo, durante el proceso de entrenamiento, podría aplicarse un peso mayor a estos materiales, con el fin de compensar su menor presencia en comparación con los textos canónicos.